### ISSUE TITLE
timersub(3) exists

### ISSUE THREAD

**Issue by alejandro-colomar** [ac000/libac#20]
https://github.com/ac000/libac/blob/ba6cffad50321c607149f468d268dd613765fcc1/src/ac_time.c#L27

You could implement most of this function as a call to timersub(3):

<https://mirrors.edge.kernel.org/pub/linux/docs/man-pages/book/man-pages-6.03.pdf#timersub_3>

```
LIBRARY
       Standard C library (libc, -lc)

SYNOPSIS
       #include <sys/time.h>

       void timeradd(struct timeval *a, struct timeval *b,
                     struct timeval *res);
       void timersub(struct timeval *a, struct timeval *b,
                     struct timeval *res);

       void timerclear(struct timeval *tvp);
       int timerisset(struct timeval *tvp);

       int timercmp(struct timeval *a, struct timeval *b, CMP);

   Feature Test Macro Requirements for glibc (see feature_test_macros(7)):

       All functions shown above:
           Since glibc 2.19:
               _DEFAULT_SOURCE
           glibc 2.19 and earlier:
               _BSD_SOURCE
```

**Comment by ac000** [comment]
Possibly, but it would mean converting a struct timespec into a struct timeval... although that would really just involve trimming the tv_nsec down to a tv_usec, but ... ;)

**Comment by alejandro-colomar** [comment]
Ahh, sorry, I meant `timerspecsub`(3).  It's in libbsd, though.  <https://manpages.debian.org/testing/libbsd-dev/timespecsub.3bsd.en.html>

**Comment by ac000** [comment]
Ah, on Linux, libac has no dependencies and I'd like to keep it that way, but good to know it's also in that library.
